
[font]
size = 10

[font.bold]
family = "SauceCodeProNerdFont"
style = "Bold"

[font.bold_italic]
family = "SauceCodeProNerdFont"
style = "Bold Italic"

[font.italic]
family = "SauceCodeProNerdFont"
style = "Italic"

[font.normal]
family = "SauceCodeProNerdFont"
style = "Regular"

[general]
import = ["/home/lee/.config/alacritty/dracula.toml"]
